version: "2"         # required to adjust maintainability checks
  checks:
    method-lines:
      config:
        threshold: 1
    argument-count:
      enabled: false

engines:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 13
      tests_patterns:
        - src/test/**

plugins:
  checkstyle:
    enabled: true
  duplication:
    enabled: true
      config:
        languages:
          java:
            mass_threshold: 20

exclude_paths:
  - build/
  - build/
  - fixtures/
  - gradle/
  - .gradle/