engines:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 13
      tests_patterns:
        - src/test/**
exclude_paths:
  - build/
  - build/
  - fixtures/
  - gradle/
  - .gradle/