version: "2"         # required to adjust maintainability checks
engines:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 13
      tests_patterns:
        - src/test/**
exclude_patterns:
  - build/
  - build/
  - fixtures/
  - gradle/
  - .gradle/
  - "**/test/"