version: "2"
engines:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 13
      tests_patterns:
        - src/test/**
  checks:
    method-lines:
      config:
        threshold: 1
    argument-count:
      enabled: false
  plugins:
    checkstyle:
      enabled: true
    duplication:
      enabled: true
        config:
          languages:
            java:
              mass_threshold: 20
exclude_paths:
  - build/
  - build/
  - fixtures/
  - gradle/
  - .gradle/