# This enables the 'defaults' to test java applications:
language: java

# We can specify a list of JDKs to be used for testing
# A list of available JDKs in Trusty can be seed in:
# https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support
jdk:
  - openjdk13

# To generate a token please use travis and heroku cli
# Warning: token will expire 04/25/2021
# https://docs.travis-ci.com/user/deployment/heroku/
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_AUTH_TOKEN

after_success:
  - bash <(curl -s https://codecov.io/bash)

    