server:
  port: ${PORT:5001}

spring:
  application:
    name: blog-microservice
  data:
    mongodb:
      uri: ${MONGODB_URI}
    redis:
      uri: ${REDIS_URI}
      channel-tag-add: ${REDIS_CHANNEL_TAG_ADD}
      channel-tag-remove: ${REDIS_CHANNEL_TAG_REMOVE}

 # security:
 #   oauth2:
 #     resourceserver:
 #       jwt:
 #         issuer-uri: ${AUTHORIZATION_SERVER}/auth/realms/blog
 #         jwk-set-uri: ${AUTHORIZATION_SERVER}/auth/realms/blog/protocol/openid-connect/certs

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3600
    lease-expiration-duration-in-seconds: 3600
    hostname: localhost
  client:
    initial-instance-info-replication-interval-seconds: 3600
    instance-info-replication-interval-seconds: 3600
    registry-fetch-interval-seconds: 3600
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}

discovery:
  uri: https://jjara-discovery.herokuapp.com/v1/discovery/


