name: build
on:
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      max-parallel: 6
      matrix:
        platform: [ ubuntu-latest ]
        java: [ '13' ]
    runs-on: ubuntu-latest
    steps:
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
          CC_TEST_REPORTER_ID: c734b38d0ac3daabba10974db54c85f78023a80edcae9a7b5002a71dd615eecc
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          # The report file must be there, otherwise Code Climate won't find it
          coverageCommand: mvn test
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco